service: coding-machine-worker

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-scripts

custom:
  dotenv:
    path: .env

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - Fn::GetAtt: [receiverQueue, Arn]
  memorySize: 512
  timeout: 30
  region: ap-south-1
  stage: ${opt:stage, 'dev'}

functions:
  receiver:
    handler: dist/handler.receiver
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - receiverQueue
              - Arn

resources:
  Resources:
    receiverQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: receiverQueue
